{ pkgs, ... }:

{
  home.packages = with pkgs; [
    fluffychat
    pkgs.yq
    pkgs.parallel
    pkgs.lftp
    pkgs.kdePackages.dolphin
    pkgs.kdePackages.dolphin-plugins
    pkgs.kdePackages.kio
    pkgs.kdePackages.kdf
    pkgs.kdePackages.kio-fuse
    pkgs.kdePackages.kio-extras
    pkgs.kdePackages.kio-admin
    pkgs.kdePackages.qtwayland
    pkgs.kdePackages.plasma-integration
    pkgs.kdePackages.kdegraphics-thumbnailers
    pkgs.kdePackages.qtsvg
    pkgs.kdePackages.kservice
    pkgs.kdePackages.gwenview
    pkgs.kdePackages.okular
    shared-mime-info
    hyprsunset
    fastfetch
    radeontop
    devbox
    lm_sensors
    graphviz
    plantuml
    dotnet-sdk
    mono
    mako
    bottom
    mission-center
    blender-hip
    cava
    clamav
    clang-tools_17
    clang_17
    cli-visualizer
    cmake
    cmake-language-server
    dex
    element-desktop
    evolution-ews
    evolutionWithPlugins
    eww
    fd
    librewolf
    fzf
    genact
    ghostscript_headless
    gimp
    git
    gnumake
    godot_4
    godot-mono
    grimblast
    gthumb
    helvum
    hyprpaper
    jetbrains.clion
    jetbrains.idea-ultimate
    jetbrains.rider
    jq
    keepassxc
    killall
    kitty
    libreoffice
    libtool
    mpvpaper
    ncmpcpp
    nixd
    nixfmt-rfc-style
    nodejs_22
    obs-studio
    obsidian
    pandoc
    pulseaudio
    razergenie
    ripgrep
    rocmPackages.clr
    rustup
    shellcheck
    socat
    sonic-pi
    spice-gtk
    steam
    steam-run
    sumneko-lua-language-server
    texlive.combined.scheme-full
    typescript
    unzip
    vlc
    vorta
    wl-clipboard-rs
    wofi
    xivlauncher
    yarn
    ymuse
    zathura
    zsh
  ];
}
