#!/usr/bin/env bash
HYPRLAND_SOCKET="UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock"
# print current window title
hyprctl activewindow -j | jq --raw-output .title

socat -u "$HYPRLAND_SOCKET" - | stdbuf -o0 awk -F '>>|,' '/^activewindow>>/{print $0}' | stdbuf -o0 cut -d"," -f2- | stdbuf -o0 awk -v len=80 '{ if (length($0) > len) print substr($0, 1, len-3) "..."; else print; }'


